name: Test and coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v4
        with:
          go-version: "1.17"
      - name: Run coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic github.com/ukautz/obsidian-meets-hugo/pkg
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
